### ISSUE TITLE
Tests failing with 0.54

### ISSUE THREAD

**Issue by genehack** [houseabsolute/List-SomeUtils-XS#1]
```
t/00-report-prereqs.t .. ok
t/ab.t ................. ok
t/Functions.t .......... 1/?     # No tests run!

#   Failed test 'No tests run for subtest "mode"'
#   at t/lib/LSU/Test/Functions.pm line 63.
Undefined subroutine &LSU::Test::Functions::mode called at t/lib/LSU/Test/Functions.pm line 1576.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 41.
t/Functions.t .......... Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/41 subtests
t/Import.t ............. ok
t/xs-only.t ............ ok
```

**Comment by autarch** [comment]
You can't really upgrade the XS module without upgrading the non-XS one. I'm not sure how to handle this in the metadata. Right now LSU (sans XS) will conditionally add LSU::XS as a prereq when installed on a system with a compiler, unless you explicitly ask for no XS.

If I also had LSU::XS depend on LSU that seems like a recipe for breakage.

**Comment by genehack** [comment]
I ran `cpan-outdated|cpanm` and it wanted to upgrade both. It upgraded the non-XS without issue, but failed on the XS with the pasted error. Re-running didn't resolve it. 

Can you tell me what sequence of upgrades I need to do to not get this error? 

-- 
John Anderson // john@genehack.org

**Comment by autarch** [comment]
Ah, I see. I suspect `cpan-outdated` listed them with the XS module first. If it had been the other way around it would've worked fine. But obviously there's no good way for `cpan-outdated` (or any other tool) to know that.

**Comment by nanis** [comment]
```text
C:\> cpan-outdated|cpanm
--> Working on D/DR/DROLSKY/List-SomeUtils-0.56.tar.gz
Fetching https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/List-SomeUtils-0.56.tar.gz ... OK
Configuring List-SomeUtils-0.56 ... OK
==> Found dependencies: List::SomeUtils::XS
--> Working on List::SomeUtils::XS
Fetching https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/List-SomeUtils-XS-0.54.tar.gz ... OK
Configuring List-SomeUtils-XS-0.54 ... OK
Building and testing List-SomeUtils-XS-0.54 ... FAIL
! Installing List::SomeUtils::XS failed. See C:\Users\sinan\.cpanm\work\1500815390.1948\build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Installed version (0.53) of List::SomeUtils::XS is not in range '0.54'
! Bailing out the installation for List-SomeUtils-0.56.
```

I do this so I can test recently released modules on Windows using MSVC 2013 compiled `perl`s.

`cpanm` downloads `List::SomeUtils`, sees `List::SomeUtils::XS` as a dependency, and therefore proceeds to try to build the XS module first.

After manually installing `List::SomeUtils` 0.56,

```text
C:\...\List-SomeUtils-0.56> cpanm List::SomeUtils::XS
--> Working on List::SomeUtils::XS
Fetching https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/List-SomeUtils-XS-0.54.tar.gz ... OK
Configuring List-SomeUtils-XS-0.54 ... OK
Building and testing List-SomeUtils-XS-0.54 ... OK
Successfully installed List-SomeUtils-XS-0.54 (upgraded from 0.53)
1 distribution installed
```

**Comment by autarch** [comment]
I just looked and relearned that there is code to deal with this in the LSU::XS tests already. They're supposed to skip if LSU isn't installed. I'll update them to skip unless LSU *0.56* is installed.
