### ISSUE TITLE
Not installing under Travis Perl 5.14

### ISSUE THREAD

**Issue by oalders** [houseabsolute/List-SomeUtils-XS#3]
See https://travis-ci.org/oalders/moosex-orderedconstruction/jobs/389475322#L5957-L6266  Looks like it's failing to install on some other Perls in that build.  Not sure what's going on or if it's even related to this module, but figured it's worth asking.

(Vaguely related, this is actually the MooseX prototype that we had discussed.  Florian had suggested a slightly different approach and we've been working on trying that out.)

**Comment by autarch** [comment]
Thanks for the report. I added something to detect compiler warnings from XS code in my dzil bundle, but this particular module emits warnings with older Perl that cannot be fixed. I just made a new release which should fix this.

**Comment by oalders** [comment]
That fixed it.  Thanks!
